# Generated by Django 6.0 on 2025-12-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-12-30'),
            preserve_default=False,
        ),
    ]
